server:
  port: ${PORT:8095}

spring:
  application:
    name: SF-PAYMENTMANAGEMENT
  security:
    username: disable
    password: disable

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-small-thunder-a1mbrg0k-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_vyjmQkB2Gh6P}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:https://stayfinder-eureka-server.onrender.com/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.pg.payment: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
