server:
  port: ${PORT:8083}

spring:
  application:
    name: SF-BOOKINGMANAGEMENT

  security:
    user:
      name: disabled
      password: disabled

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-proud-pine-a1qd69pw-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_VR45UTgJYMhc}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-psek.onrender.com/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.cdacproject.stayfinder: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
