spring:
  application:
    name: SF-PROPERTY-SERVICE

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-nameless-fog-a1hv10ul-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_rNZBv8IfTKD3}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:https://eureka-server-psek.onrender.com/eureka/}
  instance:
    prefer-ip-address: true

gateway:
  base-url: ${GATEWAY_BASE_URL:https://project-stay-finder.netlify.app}

server:
  port: ${PORT:8085}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB